### ISSUE TITLE
HttpClientHandler Support

### ISSUE THREAD

**Issue by wuyu8512** [TelegramBotsAPI/Telegram.Bots#7]
In my country, I need a WebProxy to access telegram, can you add HttpClientHandler Support？

**Comment by AmanAgnihotri** [comment]
Hello! Thank you for considering `Telegram.Bots` for your bot project.

In this library, the ideal way of initializing the `BotClient` is through the dependency injection mechanism. The [AddBotClient](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/ModuleExtensions.cs#L22) extension method returns an `IHttpClientBuilder` which you can then use to setup your proxy, I imagine. I say "I imagine" because I have never set this up myself and so do not fully know whether this will work but I kept the option open nonetheless and here is what I think you can do to get your web proxy working as well:

```csharp
using System;
using Microsoft.Extensions.DependencyInjection;
using Telegram.Bots;

IServiceProvider provider = new ServiceCollection()
  .AddBotClient("<bot-token>")
  .ConfigurePrimaryHttpMessageHandler(() => new SocketsHttpHandler
  {
    Proxy = new WebProxy(Host: "<your-host>", Port: 1234),
    UseProxy = true
  })
  .Services
  .BuildServiceProvider();

IBotClient bot = provider.GetRequiredService<IBotClient>();
```

You can further add more `HttpClientHandler` by calling `AddHttpMessageHandler` accordingly.

Do let me know if this resolves your issue and I can setup a decent example in the README about using the web proxy then. You can also tell me what you wrote so I can use that as inspiration for the example that can be in the README for future users who also need a web proxy.

**Comment by wuyu8512** [comment]
It's good and solved my issue, thanks!!
