### ISSUE TITLE
TimeOut Cant Set int.MaxValue

### ISSUE THREAD

**Issue by wuyu8512** [TelegramBotsAPI/Telegram.Bots#8]
Consider changing int to TimeSpan?

**Comment by AmanAgnihotri** [comment]
When you talk about the timeout value, I imagine you mean the [Timeout](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/Configs/BotConfig.cs#L15) property made available by the [BotConfig](https://github.com/TelegramBotsAPI/Telegram.Bots/blob/master/src/Telegram.Bots/Configs/BotConfig.cs) class.

I made this property an `int` type so as to make it configurable from the `appsettings.json` or any other configuration file that `IConfiguration` can load as a section.

Even the `HttpClient`'s internal implementation is such that `2147483` is the maximum integer timeout you can setup with `BotClient` which amounts to some 24.85 days. Another alternative for `HttpClient` is the infinite timeout but I personally do not think it would be wise to use that as it will block the `HttpClient` forever should the upstream service never responds. Telegram anyway times out the bot requests, if I recall correctly. At least that was my experience with `GetUpdates` based requests during polling.

Why would you want to setup an `int.MaxValue` based timeout anyway? HttpClient will fail there as it imposes a limit on its maximum `TimeSpan` unless the `TimeSpan` denotes infinite time.

**Comment by wuyu8512** [comment]
Hi, thank you very much for your answers, in fact, I will upload some large files, but the speed of uploading to server using `bot api(--local)` is very slow (this may be my problem), so I would like to have a longer time to wait, but Actually it will not exceed 24 days

> Even the `HttpClient`'s internal implementation is such

I'm glad to hear this detail，I think this question is actually irrelevant, maybe we can set it to `System.Threading.Timeout.Infinite` to represent infinite waiting

**Comment by AmanAgnihotri** [comment]
Unless you are using the local Telegram Bot Server, the upload limit for a bot using the HTTP Bot API is 50 MB and the download limit for the same is 20 MB. If you are using the local Telegram Bot Server, the upload limit becomes 2000 MB and the download limit does not exist (and I guess that'd be practically 2000 MB only).

I will caution against the use of Infinite timeout for various reasons.

Even 2000 MB limit should sit well with timeout set as `2147483` seconds which is the maximum integer you can go in `HttpClient`. With a 10 kbps connection, 2000 MB will take like 18.5 days to send which is under 24 days.

You will have to re-implement the `AddBotClient` extension method for your very specific use-case to setup Infinite timeout. Doable but need not be done given your situation.

I would like to keep the Timeout property as an int to allow for its setup through `appsettings.json` itself.

**Comment by wuyu8512** [comment]
> I would like to keep the Timeout property as an int to allow for its setup through `appsettings.json` itself.

`System.Threading.Timeout.Infinite` is an integer constant, value is `-1`

**Comment by AmanAgnihotri** [comment]
Ah, I did not know that `System.Threading.Timeout.Infinite` is equivalent to the `-1` value. Unfortunately, I tried setting `-1` as the value of the `Timeout` property and the program still blew up. After digging a bit, I figured that it is just as possible and perhaps even more readable to setup `TimeSpan` in likes of `appsettings.json`. 

Here is an article which shows how to do that:

[TimeSpan configuration values in .NET Core by Mark Seeman](https://blog.ploeh.dk/2019/11/25/timespan-configuration-values-in-net-core/)

Since this meets my requirement of allowing timeouts to be configurable from `appsettings.json` file, I set the `Timeout` property to `TimeSpan` type in the following commit:

[Make Timeout a TimeSpan Type](https://github.com/TelegramBotsAPI/Telegram.Bots/commit/402220cb6055cf2ce359a423c505b7e49279ff28)

Since this way one can also setup the timeout to an `InfiniteTimeSpan` which was not possible before since `-1` and `InfiniteTimeSpan` are not equivalent for the `HttpClient` which complained for `-1` timeout value.

I also made this available as a [NuGet](https://www.nuget.org/packages/Telegram.Bots/5.1.0) package.
