### ISSUE TITLE
SendPhoto use MemoryStream is it possible?

### ISSUE THREAD

**Issue by Eatric** [TelegramBotsAPI/Telegram.Bots#9]
When i trying to send photo with MemoryStream I get this:

`Send Telegram photo {"ChatId":304667397, "Photo":{"Id":"79d1d33d-f54b-48a1-b337-b557622baad5", "Data":"System.IO.MemoryStream"}, "Method":"sendPhoto"} and get response {"Failure":{"Description":"Bad Request: file must be non-empty", "ErrorCode":400}, "Ok":false}.`

Data is just use MemoryStream.ToString()? 

Can you help me?

**Comment by Eatric** [comment]
I get the bytes of image from Selenium WebDriver so, there is no file name in bytes maybe that call the exception in code example?

**Comment by AmanAgnihotri** [comment]
As long as the bytes you get represent a proper image format (like JPEG or PNG), the lack of name is not an issue because `InputFile` class automatically generates a GUID as the identifier/name for the stream representing the image.

The code I showed as an example works. You are not supposed to call the `ToString` function on the stream as that will be problematic. Just pass the stream to the `SendPhotoFile`  function along with the chat id and it should be good.

In the example you showed, you were successful in writing the stream you got to a file with png extension and then read the file and send it to Telegram using the `SendPhotoFile` method. So, you should be able to pass the stream directly to the method and have it working without any issue.
